name: Deploy Fake
on: 
    workflow_call: 
        secrets:
            ambiente:
                required: true 
                description: "Ambiente onde vai ser feito o deploy"
jobs:
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.AMBIENTE_ENTREGA }}"
            - name: Curl Deploy no ambiente
              run: "curl -X POST https://webhook.site/60277936-9bf4-4538-97cd-c8a1157e1953 -d '{ ambiente: ${{ secrets.AMBIENTE_ENTREGA }}}'"