name: CI/CD Fake
on: 
    workflow_dispatch: 
jobs:
    CI:
        runs-on: ubuntu-latest
        env:
          USER_NAME: "FABRICIO VERONEZ"
        steps:
            - name: Build de Imagem Docker
              run: echo "Execução do comando de docker build"
            - name: Execução de Testes de Software
              run: echo "Aqui eu executo o teste de software"
            - name: Publicando a Release
              run: echo "Publicação da Relase final"
            - run: |
                echo "::add-mask:: $USER_NAME"
            - run: echo "USER_ID is $USER_NAME"
            - name: Adicionando mensagens de Log
              run: |
                echo "::debug:: Mensagem de Log Debug"
                echo "::warning:: Mensagem de Log Warning" 
                echo "::notice:: Mensagem de Log Notice" 
                echo "::error:: Mensagem de Log Error"
    CD:
      needs: [CI]
      uses: fsv-aula/repo-deploy/.github/workflows/deploy.yml@main
      with:
        ambiente: desenvolvimento
